# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CJHtest', '0003_auto_20161021_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
